#!/bin/sh
##################################################################
#                                                                #
#    Build System Contributions by:                              #
#                                                                #		
#    * Mike Brancato - Debian patches & build support            #
#                                                                #
##################################################################

#---------------------------------------------#
#             pseudo-configure                #
#---------------------------------------------#

if [ ! -e obj_files ] ; then
  mkdir obj_files
else
  rm -rf obj_files/*
fi

OS=`uname -s | cut -d '_' -f1`

if (test $OS = Darwin) || (test $OS = Linux) ; then
  ## I only have unicode typefaces under Mac OS X ##
  ## so its the only platform I can test under properly ##

  ## comment out the 'if ...' and 'fi' lines encasing ##
  ## the EXTRA_CPP_FLAGS line to test on other platforms ##
  
  EXTRA_CPP_FLAGS="-DUSE_ICONV_CONVERSION"
fi

#---------------------------------------------#
#                 Compiling                   #
#---------------------------------------------#

echo "Compiling AtomicParsley_genres.cpp ..."

g++ -g -O2 -Wall -MT obj_files/AtomicParsley_genres.o -MD -MP -MF "./obj_files/AtomicParsley_genres.Tpo" -c -o obj_files/AtomicParsley_genres.o AtomicParsley_genres.cpp

echo "Compiling AP_iconv.cpp ..."

g++ -g -O2 -Wall -MT AP_iconv.o -MD -MP -MF "./obj_files/AP_iconv.Tpo" -c -o obj_files/AP_iconv.o AP_iconv.cpp

if test $OS = Darwin ; then
  echo "Compiling AP_NSImage.cpp ..."

  g++ -g -O2 -Wall -MT obj_files/AP_NSImage.o -MD -MP -MF "./obj_files/AP_NSImage.Tpo" -c -o obj_files/AP_NSImage.o AP_NSImage.mm
fi

echo "Compiling AtomicParsley.cpp ..."

g++ -g -O2 -Wall -Wno-unused $EXTRA_CPP_FLAGS -MT obj_files/AtomicParsley.o -MD -MP -MF "./obj_files/AtomicParsley.Tpo" -c -o obj_files/AtomicParsley.o AtomicParsley.cpp

echo "Compiling main.cpp ..."

g++ -g -O2 -Wall -I../AtomicParsley -MT obj_files/main.o -MD -MP -MF "./obj_files/main.Tpo" -c -o obj_files/main.o main.cpp

#---------------------------------------------#
#                  Linking                    #
#---------------------------------------------#
echo "Linking AtomicParsley..."

if test $OS = Darwin ; then
  g++ -g -O2 -Wall -liconv -framework Cocoa -o AtomicParsley obj_files/AtomicParsley_genres.o obj_files/AP_iconv.o obj_files/AP_NSImage.o obj_files/AtomicParsley.o obj_files/main.o

elif test $OS = Linux ; then
  g++ -Wl,-headerpad -g -O2 -Wall -o AtomicParsley obj_files/AtomicParsley_genres.o obj_files/AP_iconv.o obj_files/AtomicParsley.o obj_files/main.o

elif test $OS = CYGWIN ; then
  g++ -g -O2 -Wall -o AtomicParsley.exe  obj_files/AtomicParsley_genres.o obj_files/AP_iconv.o obj_files/AtomicParsley.o obj_files/main.o -liconv -lgcc 

else
  g++ -g -O2 -Wall -liconv -o AtomicParsley.exe obj_files/AtomicParsley_genres.o obj_files/AP_iconv.o obj_files/AtomicParsley.o obj_files/main.o
fi

#---------------------------------------------#
#    Stripping (enabled on Mac OS X only)     #
#---------------------------------------------#

if test $OS = Darwin ; then
  strip -x AtomicParsley 
fi
